<?php

namespace F4\LibraryBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuantityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuantityRepository extends EntityRepository
{
}
