<?php

namespace F4\LibraryBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuantityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuantityRepository extends EntityRepository
{
    public function getInStockQuantity($id)
    {
        $q = $this->createQueryBuilder('q')
            ->leftJoin('F4LibraryBundle:Reservation', 'r', 'WITH', 'q.id = r.bookUnit')
            ->where('q.book = :bookId AND r.bookUnit is NULL')
            ->setParameter('bookId', $id)
            ->setMaxResults(1);

        $result = $q->getQuery()->getOneOrNullResult();

        return $result;
    }
}
