<?php

namespace F4\LibraryBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
    public function getReservedBooks($user = null, $taken = false)
    {
        $args = array();
        $args['bookTaken'] = $taken;

        if (false == is_null($user)) {
            $args['user'] = $user;
        }

        $result = $this->findBy($args, array('id' => 'DESC'));

        return $result;
    }
}
