# src/F4/LibraryBundle/Resources/config/routing.yml
F4LibraryBundle_homepage:
    pattern:  /
    defaults: { _controller: F4LibraryBundle:Page:index }
    requirements:
        _method:  GET

F4LibraryBundle_book:
    pattern:  /book/{id}
    defaults: { _controller: F4LibraryBundle:Page:bookPage }
    requirements:
        _method:  GET
        id: \d+

F4LibraryBundle_tag:
    pattern:  /tag/{id}
    defaults: { _controller: F4LibraryBundle:Page:tagPage }
    requirements:
        _method:  GET
        id: \d+

F4LibraryBundle_author:
    pattern:  /author/{id}
    defaults: { _controller: F4LibraryBundle:Page:authorPage }
    requirements:
        _method:  GET
        id: \d+

F4LibraryBundle_ajax_call:
    pattern:  /ajax/{list}/{limit}/{page}/{uid}
    defaults: { _controller: F4LibraryBundle:Ajax:listBooks, uid: 0, limit: 3, page: 1 }
    requirements:
        _method:  GET
        list: \w+
        limit: \d+
        page: \d+
        uid: \d+
