# src/F4/LibraryBundle/Resources/config/routing.yml
F4LibraryBundle_homepage:
    pattern:  /
    defaults: { _controller: F4LibraryBundle:Page:index }
    requirements:
        _method:  GET

F4LibraryBundle_book:
    pattern:  /book/{id}
    defaults: { _controller: F4LibraryBundle:Book:show }
    requirements:
        _method:  GET
        id: \d+

F4LibraryBundle_ajax_call:
  pattern:  /book/ajax/call
  defaults: { _controller: F4LibraryBundle:Page:ajax }
  requirements:
        _method:  GET|POST