# src/F4/LibraryBundle/Resources/config/routing.yml
F4LibraryBundle_homepage:
    pattern:  /
    defaults: { _controller: F4LibraryBundle:Page:index }
    requirements:
        _method:  GET

F4LibraryBundle_contact:
    pattern:  /contact
    defaults: { _controller: F4LibraryBundle:Page:contact }
    requirements:
        _method:  GET|POST

F4LibraryBundle_book:
    pattern:  /book/{id}
    defaults: { _controller: F4LibraryBundle:Book:show }
    requirements:
        _method:  GET
        id: \d+